default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: vsm
  password: ludwig2406
  host: <%= ENV["DB_HOST"] || "localhost" %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "hardlopen_metvirgil_dev") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "hardlopen_metvirgil_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION", "hardlopen_metvirgil") %>